// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA27yMPyCuJID-gW_LdTwDIscopBIpGVAw',
    appId: '1:439232034927:web:dfaad167314710fcddf59a',
    messagingSenderId: '439232034927',
    projectId: 'chirp-aid-8c7f6',
    authDomain: 'chirp-aid-8c7f6.firebaseapp.com',
    storageBucket: 'chirp-aid-8c7f6.appspot.com',
    measurementId: 'G-HBGKQXBT7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYBlGAhM2Bc0abiOToyl5J3eAR4Vtnouw',
    appId: '1:439232034927:android:fa2a3f2cab0c7c6eddf59a',
    messagingSenderId: '439232034927',
    projectId: 'chirp-aid-8c7f6',
    storageBucket: 'chirp-aid-8c7f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiacQOtfdopQ1kM5A5LNM1QqRod2Ni9Eo',
    appId: '1:439232034927:ios:e8caa145d98d08e1ddf59a',
    messagingSenderId: '439232034927',
    projectId: 'chirp-aid-8c7f6',
    storageBucket: 'chirp-aid-8c7f6.appspot.com',
    iosBundleId: 'com.example.chripAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiacQOtfdopQ1kM5A5LNM1QqRod2Ni9Eo',
    appId: '1:439232034927:ios:e8caa145d98d08e1ddf59a',
    messagingSenderId: '439232034927',
    projectId: 'chirp-aid-8c7f6',
    storageBucket: 'chirp-aid-8c7f6.appspot.com',
    iosBundleId: 'com.example.chripAid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA27yMPyCuJID-gW_LdTwDIscopBIpGVAw',
    appId: '1:439232034927:web:f792f6ce4c0fd994ddf59a',
    messagingSenderId: '439232034927',
    projectId: 'chirp-aid-8c7f6',
    authDomain: 'chirp-aid-8c7f6.firebaseapp.com',
    storageBucket: 'chirp-aid-8c7f6.appspot.com',
    measurementId: 'G-CCR87RC3WL',
  );
}
